---

- name: stop zookeeper service
  service:
    name: zookeeper
    state: stopped
    enabled: no

- name: stop mesos-master service
  service:
      name: mesos-master
      state: stopped
      enabled: no

- name: start mesos-slave service
  service:
      name: mesos-slave
      state: started
      enabled: yes