---

#Handlers for the masters
- name: restart zookeeper
	service:
		name: zookeeper
		state: restarted

- name: stop mesos-slave
	service:
		name: mesos-slave
		enabled: no
		state: stopped

- name: start mesos-master
	service:
		name: mesos-master
		enabled: yes
		state: started