---

#standalone setup file

--- #setup mesos on masters
- hosts: standalone
  remote_user: user
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  roles: 
    - common
    - standalone
    - marathon