--- #setup mesos on masters
- hosts: masters
  remote_user: user
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars: 
    install_mode: "{{ install_mode|default('cluster') }}"
  roles: 
    - common