
#main ansible yml file

#Test whether the extra-vars is set properly
- name: check install_mode value
  hosts: local
  connection: local
  vars: 
    install_mode: "{{ install_mode|default('cluster') }}"
  tasks:
   - name: reject all install_mode but cluster or standalone
     fail: msg="Only install_mode=cluster and install_mode=standalone are supported"
     when: (install_mode != "cluster") and (install_mode != "standalone") 

#playbook for master(s) setup
- include: setup-masters.yml
  when: install_mode == "cluster"

#playbook for slave(s) setup
- include: setup-slaves.yml
  when: install_mode == "cluster"

- include: setup-standalone.yml
  when: install_mode == "standalone"
