--- #main ansible yml file

#Reject everything but cluster for install_mode since only implemented solution for now
  tasks: 
    - name: reject all install_mode but cluster
      fail: msg="Only install_mode=cluster is supported at the moment"
      when: install_mode != "cluster"
#playbook for master(s) setup
- include: setup-masters.yml

#playbook for slave(s) setup
#- include: setup-slaves.yml

#playbook for marathon setup
#- include: setup-marathon.yml